import type { FaqItem } from "@/components/Faq";

/** Shared by the page's FAQPage JSON-LD and the rendered accordion. */
export const FAQS: FaqItem[] = [
  {
    question: "How are the random numbers generated?",
    answer:
      "The tool uses the browser's crypto.getRandomValues() API, which generates cryptographically secure pseudorandom numbers using the operating system's entropy pool. This is much higher quality than Math.random().",
  },
  {
    question: "What is the maximum number of values I can generate?",
    answer:
      "You can generate up to 500 numbers at once. For larger batches, generate multiple sets and combine them.",
  },
  {
    question: "How does the 'Unique only' option work?",
    answer:
      "With unique mode on, each generated number can only appear once in the result set. The range must be large enough to contain the requested count of unique integers.",
  },
  {
    question: "Can I generate decimal numbers?",
    answer:
      "Yes. Toggle 'Decimals' on and the generator will produce numbers with up to 4 decimal places within your specified range. The min and max values can also be decimals.",
  },
  {
    question: "Is a random number between 1 and 10 truly uniform?",
    answer:
      "Yes. The generator maps the random bytes to your range using floating-point arithmetic, ensuring all values in the range are equally likely. Edge values (min and max) are included.",
  },
  {
    question: "What is the difference between random and pseudorandom?",
    answer:
      "True randomness requires a physical entropy source (atmospheric noise, radioactive decay). Pseudorandom numbers are generated by algorithms that produce sequences indistinguishable from random for practical purposes. The crypto API uses the OS entropy pool, making it suitable for security-sensitive uses.",
  },
];
