import type { Metadata } from "next";
import Link from "next/link";
import { ChevronRight } from "lucide-react";
import RandomNumberGenerator from "./RandomNumberGenerator";

export const metadata: Metadata = {
  title: "Free Random Number Generator — Single or Bulk, Integer or Decimal",
  description:
    "Generate random numbers within any range. Choose count (up to 500), integers or decimals, unique values only, and ascending sort. Copy or use instantly. Free, browser-based.",
  keywords: [
    "random number generator", "random number generator online", "generate random numbers",
    "random integer generator", "random number between 1 and 100", "bulk random numbers",
    "unique random number generator", "random number picker", "lottery number generator",
  ],
  alternates: { canonical: "https://mohdsakib.vercel.app/tools/random-number-generator" },
  openGraph: {
    title: "Free Random Number Generator",
    description: "Generate random numbers in any range — single or bulk, integers or decimals, unique only.",
    url: "https://mohdsakib.vercel.app/tools/random-number-generator",
    type: "website",
  },
};

const USES = [
  { icon: "🎲", title: "Games & Decisions",     desc: "Pick a random player order, settle a dispute, roll a virtual die." },
  { icon: "🎰", title: "Lottery & Raffles",      desc: "Generate unique lottery numbers or pick random raffle winners." },
  { icon: "📊", title: "Statistics & Sampling",  desc: "Create random samples for surveys, simulations, or A/B test assignments." },
  { icon: "🧑‍💻", title: "Software Testing",       desc: "Generate test data with random IDs, port numbers, or seed values." },
  { icon: "🏫", title: "Education",              desc: "Teachers use random numbers for student grouping or picking who answers next." },
  { icon: "🎨", title: "Creative Projects",       desc: "Pick a random colour code, chapter, page, or creative prompt." },
];

const FAQS = [
  { q: "How are the random numbers generated?", a: "The tool uses the browser's crypto.getRandomValues() API, which generates cryptographically secure pseudorandom numbers using the operating system's entropy pool. This is much higher quality than Math.random()." },
  { q: "What is the maximum number of values I can generate?", a: "You can generate up to 500 numbers at once. For larger batches, generate multiple sets and combine them." },
  { q: "How does the 'Unique only' option work?", a: "With unique mode on, each generated number can only appear once in the result set. The range must be large enough to contain the requested count of unique integers." },
  { q: "Can I generate decimal numbers?", a: "Yes. Toggle 'Decimals' on and the generator will produce numbers with up to 4 decimal places within your specified range. The min and max values can also be decimals." },
  { q: "Is a random number between 1 and 10 truly uniform?", a: "Yes. The generator maps the random bytes to your range using floating-point arithmetic, ensuring all values in the range are equally likely. Edge values (min and max) are included." },
  { q: "What is the difference between random and pseudorandom?", a: "True randomness requires a physical entropy source (atmospheric noise, radioactive decay). Pseudorandom numbers are generated by algorithms that produce sequences indistinguishable from random for practical purposes. The crypto API uses the OS entropy pool, making it suitable for security-sensitive uses." },
];

export default function RandomNumberGeneratorPage() {
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQS.map(({ q, a }) => ({
      "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a },
    })),
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <div className="min-h-screen" style={{ background: "#faf8ff" }}>
        <header className="fixed top-0 left-0 right-0 z-50 backdrop-blur-md"
          style={{ background: "rgba(250,248,255,0.92)", borderBottom: "1px solid rgba(124,58,237,0.1)" }}>
          <div className="max-w-3xl mx-auto px-6 h-13 flex items-center justify-between">
            <nav className="flex items-center gap-1.5" style={{ color: "rgba(3,3,2,0.4)", fontSize: "12px" }}>
              <Link href="/" className="font-medium hover:text-[#1c1b18] transition-colors" style={{ color: "inherit" }}>Sakib</Link>
              <ChevronRight size={11} style={{ opacity: 0.4 }} />
              <Link href="/tools" className="hover:text-[#1c1b18] transition-colors" style={{ color: "inherit" }}>Tools</Link>
              <ChevronRight size={11} style={{ opacity: 0.4 }} />
              <span style={{ color: "#7c3aed", fontWeight: 500 }}>Random Number Generator</span>
            </nav>
            <Link href="/tools" className="hover:opacity-80 transition-opacity"
              style={{ fontSize: "10px", fontWeight: 600, letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(3,3,2,0.4)" }}>
              All tools
            </Link>
          </div>
        </header>

        <main className="max-w-3xl mx-auto px-6 pt-24 pb-20">
          <div className="mb-8">
            <div className="inline-flex items-center gap-2 mb-4 px-3 py-1.5 rounded-full text-[10px] font-semibold"
              style={{ background: "#f5f3ff", color: "#7c3aed", border: "1px solid #ddd6fe" }}>
              🎲 CALCULATORS
            </div>
            <h1 className="font-semibold tracking-tight leading-tight mb-2.5"
              style={{ fontSize: "clamp(26px,4vw,34px)", color: "#1c1b18" }}>
              Random Number Generator
            </h1>
            <p style={{ fontSize: "13.5px", color: "rgba(3,3,2,0.45)", lineHeight: 1.65 }}>
              Set your range and count — get cryptographically random results instantly.
            </p>
          </div>
          <RandomNumberGenerator />
        </main>

        <div style={{ borderTop: "1px solid rgba(124,58,237,0.08)" }}>
          <div className="max-w-3xl mx-auto px-6 py-20 space-y-20">

            <section>
              <h2 className="font-semibold tracking-tight mb-4" style={{ fontSize: "21px", color: "#1c1b18" }}>
                What is a Random Number Generator?
              </h2>
              <p style={{ fontSize: "14px", color: "rgba(3,3,2,0.55)", lineHeight: 1.85 }}>
                A random number generator produces numbers with no discernible pattern — each number in the range
                is equally likely. True randomness has applications across gaming, statistics, cryptography, education,
                and decision-making. This tool uses the browser's cryptographic random API to generate high-quality
                random numbers with no predictable sequence.
              </p>
            </section>

            <section>
              <h2 className="font-semibold tracking-tight mb-6" style={{ fontSize: "21px", color: "#1c1b18" }}>Common Uses</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {USES.map(({ icon, title, desc }) => (
                  <div key={title} className="rounded-[14px] p-5"
                    style={{ background: "#ffffff", boxShadow: "0 0 0 1px rgba(3,3,2,0.06)", border: "1px solid rgba(124,58,237,0.08)" }}>
                    <p className="font-semibold mb-1" style={{ fontSize: "13.5px", color: "#1c1b18" }}>{icon} {title}</p>
                    <p style={{ fontSize: "12.5px", color: "rgba(3,3,2,0.5)", lineHeight: 1.7 }}>{desc}</p>
                  </div>
                ))}
              </div>
            </section>

            <section>
              <h2 className="font-semibold tracking-tight mb-6" style={{ fontSize: "21px", color: "#1c1b18" }}>Frequently Asked Questions</h2>
              <div className="space-y-px rounded-[16px] overflow-hidden" style={{ boxShadow: "0 0 0 1px rgba(3,3,2,0.06)" }}>
                {FAQS.map(({ q, a }, i) => (
                  <div key={i} className="px-6 py-5"
                    style={{ background: "#ffffff", borderBottom: i < FAQS.length - 1 ? "1px solid rgba(3,3,2,0.05)" : "none" }}>
                    <p className="font-medium mb-2" style={{ fontSize: "14px", color: "#1c1b18" }}>{q}</p>
                    <p style={{ fontSize: "13px", color: "rgba(3,3,2,0.5)", lineHeight: 1.75 }}>{a}</p>
                  </div>
                ))}
              </div>
            </section>

            <section className="rounded-[20px] px-8 py-10 text-center"
              style={{ background: "linear-gradient(135deg, #4f46e5, #7c3aed)", boxShadow: "0 8px 40px rgba(124,58,237,0.25)" }}>
              <p className="font-semibold tracking-tight mb-2" style={{ fontSize: "19px", color: "#ffffff" }}>More free tools</p>
              <p className="mb-6" style={{ fontSize: "13px", color: "rgba(255,255,255,0.6)", lineHeight: 1.7 }}>
                Age calculator, percentage calculator, unit converter and more.
              </p>
              <Link href="/tools" className="inline-flex items-center gap-2 px-6 py-3 rounded-[10px] font-medium transition-opacity hover:opacity-80"
                style={{ background: "#ffffff", color: "#7c3aed", fontSize: "13px" }}>
                Browse all tools
              </Link>
            </section>

            <div className="pb-4">
              <Link href="/tools" className="inline-flex items-center gap-2.5 hover:opacity-70 transition-opacity"
                style={{ fontSize: "11px", fontWeight: 600, letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(3,3,2,0.35)" }}>
                <span>←</span> Back to tools
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
